version: '3'
services:
  userDB:
    image: postgres:latest
    container_name: bookingDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  hotelDB:
    image: postgres:latest
    container_name: hotelDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hotel
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  authDB:
    image: postgres:latest
    container_name: authDB
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data