Auth:
  JwtSecretKey: "AllYourBase"
HttpServer:
  Port: 9234
  ShutdownTimeout: 2m
Database:
  Main:
    Host: '127.0.0.1'
    Port: '3306'
    User: 'root'
    Password: 'root'
    Name: 'service'
  Replica:
    Host: '127.0.0.1'
    Port: '3306'
    User: 'root'
    Password: 'root'
    Name: 'service'
