basePath: /v2
definitions:
  http.Account:
    properties:
      balance:
        type: integer
      currency:
        type: string
      id:
        type: integer
      userID:
        type: integer
    type: object
  http.AccountTransaction:
    properties:
      currency:
        type: string
      from_id:
        type: integer
      id:
        type: integer
      message:
        type: string
      money:
        type: integer
      time:
        type: string
      to_id:
        type: integer
    type: object
  http.Card:
    properties:
      cvc:
        type: integer
      exp:
        type: string
      fullName:
        type: string
      id:
        type: integer
      requisite:
        type: string
    type: object
host: localhost:8082
info:
  contact: {}
  description: Payment service API in Go using Gin Framework
  title: Payment Service API
  version: "1.0"
paths:
  /account:
    post:
      description: Create Account for user with balance and currency. Need Authorization
        Header and currency
      parameters:
      - description: CreateAccount
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.Account'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Account for user
  /account/:id:
    delete:
      description: Delete User Account with balance and currency. Need Authorization
        Header and account id
      responses:
        "200":
          description: OK
      summary: Delete User Account
    get:
      description: Get user's account by id. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: get user's account by id
  /account/payment:
    post:
      description: Create Payment from account to account. Need Authorization Header
        and account id
      parameters:
      - description: CreateAccountPayment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.AccountTransaction'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Payment from account to account
  /account/payment/:id:
    get:
      description: Get from account to account payment. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: account to account payment
  /account/payments:
    get:
      description: Get All from account to account payments. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: account to account payment
  /accounts:
    get:
      description: Get user's all accounts. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: get user's all accounts
  /card:
    post:
      description: Get Card data from request and create card for user. Need Authorization
        Header
      parameters:
      - description: CreateCard
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Card for user
  /card/:id:
    delete:
      description: Get Card id for delete user card. Need Authorization Header
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Card for user
    put:
      description: Get Card data from request and card id for update user card. Need
        Authorization Header
      parameters:
      - description: UpdateCardCard
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Update Card for user
  /card/payment:
    post:
      description: Create Payment from card to card. Need Authorization Header and
        Card id
      parameters:
      - description: CreateCardPayment
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.Card'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Create Payment from card to card
  /card/payment/:id:
    get:
      description: Get Payments from card to card payment. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: card to card payment
  /card/payments:
    get:
      description: Get Payments from card to card payments. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: card to card payments
  /cards:
    get:
      description: Get user's all cards. Need Authorization Header
      responses:
        "200":
          description: OK
      summary: get user's all cards
swagger: "2.0"
