HttpServer:
  Port: 9234

Database:
  Main:
    Host: '127.0.0.1'
    SslMode: 'disable'
    Port: '5433'
    User: 'postgres'
    Password: 'postgres'
    DbName: 'hotel'
  Replica:
    Host: '127.0.0.1'
    SslMode: 'disable'
    Port: '5433'
    User: 'postgres'
    Password: 'postgres'
    DbName: 'hotel'
