global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  #first rule
  #second rule

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9236','host.docker.internal:9237']
        labels:
          group: 'user'

      - targets: ['host.docker.internal:9234','host.docker.internal:9235']
        labels:
          group: 'booking'

      - targets: [ 'host.docker.internal:9233']
        labels:
          group: 'auth'