Auth:
  JwtSecretKey: "gabdyq"
  PasswordSecretKey: "#Gzh87710375053"
Redis:
  Address: 'localhost:6543'
GrpcServer:
  Port: ":9090"
Database:
  Main:
    Host:     'localhost'
    Port:     '5432'
    User:     'postgres'
    Password: '12345'
    DBName:   'payservice'
  Replica:
    Host:     'localhost'
    Port:     '5432'
    User:     'postgres'
    Password: '12345'
    DBName:   'payservice'