definitions:
  entity.SwagConfResponse:
    properties:
      message:
        type: string
    type: object
  entity.SwagConfirmInput:
    properties:
      code:
        type: integer
      id:
        type: integer
    type: object
  entity.SwagResponce:
    properties:
      id:
        type: integer
      message:
        type: string
    type: object
host: localhost:9234
info:
  contact: {}
  description: Booking service
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Booking service
  version: "1.0"
paths:
  /api/booking/v1/booking/book/{id}:
    get:
      consumes:
      - application/json
      description: Book room
      parameters:
      - description: hotel id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SwagResponce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.SwagResponce'
      security:
      - BearerAuth: []
      summary: Book room
      tags:
      - booking
  /api/booking/v1/booking/hotel/confirm:
    post:
      consumes:
      - application/json
      description: Book room
      parameters:
      - description: id and code
        in: body
        name: swagInput
        required: true
        schema:
          $ref: '#/definitions/entity.SwagConfirmInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.SwagConfResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/entity.SwagConfResponse'
      security:
      - BearerAuth: []
      summary: Book room
      tags:
      - booking
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
